### PR TITLE
Changes from impc-integration branch

### PR DESCRIPTION
**Pull request by yuanzhou**
In the last three months, we've been actively making changes during the IMPC integration process. In order to push Phenogrid to IMPC site, we've made both design and internal data loading changes. It also made Phengorid a more generic tool to be used in other 3rd party web apps. Please refer to the commit history for changes have been made since this list if too long.

@harryhoch since this PR can't be auto-merged due to so many changes, and the current master branch (npm v1.2.7) has already been tagged and archived as release, as well as published on npmjs.org. Can I suggest that we simply overwrite the master with all the impc-integration code to ease the merging process? So we don't have to manually resolve all the conflicts. This PR is created to mark this change. Any thoughts?

### CODE REVIEW

**Comment by harryhoch** [comment]
@yuanzhou, are there no changes in master that are needed?  Please verify that over-writing wouldn't lose anything important.

If we do overwrite, this would become v 1.3.0? That sounds reasonable to me.  

Before overwriting, please ensure that all travis tests pass..

**Comment by yuanzhou** [comment]
@harryhoch, thanks for reminding me this. I compared the master branch with this impc branch, and noticed that the impc branch is based on the v1.2.4, and I had also made changes to the master branch while I was working on the impc branch. So I'll check carefully what are the changes made between v1.2.4 and the current v1.2.7, then apply necessary changes to impc. We may be able to auto merge by then. Or at least we won't lose changes made in master but not in impc.

**Comment by harryhoch** [comment]
@yuanzhou, thanks. I'm guessing it shouldn't be that hard to reconcile.

**Comment by yuanzhou** [comment]
FYI @harryhoch, I updated things that the impc-integration is behind, and after trying to merge impc-integration into master using Git commands, I noticed that the merging conflicts are caused by `index.html`, `package.json`, and the generated `phenogrid-bundle.js`, all other code can be merged automatically. So I resolved those conflicts easily and committed the merge. Will test before publishing to npm registry.

**Comment by harryhoch** [comment]
Sounds great, @yuanzhou, thanks!

**Pull request merged**
