### PR TITLE
fixed #249 and edit No similarity matches to be a single line

### LINKED ISSUE #249: Add options menu to top left
With the increase in the number of species in phenogrid, it is now usually impossible to see the options menu until well below the fold. I recommend moving the menu to the top left where it will be more readily seen. This recommendation is for both analyze phenotypes and for the compare tab. Thoughts? This could also be a quick fix for the c elegans duplication issue. https://github.com/monarch-initiative/monarch-app/issues/1304

 
screen shot 2016-07-11 at 5 19 59 pm
----------------------------------THE FOLD LIES HERE ----------------------------------
     screen shot 2016-07-11 at 5 20 10 pm

Related to https://github.com/monarch-initiative/phenogrid/issues/224

### PR DESCRIPTION
**Pull request by cborromeo**
@harryhoch  can you check these changes?

### CODE REVIEW

**Comment by harryhoch** [comment]
looks good on its own. Have you tested within monarch-app?

**Comment by cborromeo** [comment]
Yes.  Here it is using diabetes mellitus 2  
test_pic

**Comment by harryhoch** [comment]
This looks fantastic. thanks for digging in.

**Comment by jmcmurry** [comment]
Woot! Thanks all

On Wednesday, July 13, 2016, Harry Hochheiser <notifications@github.com>
wrote:

> Merged #250 <https://github.com/monarch-initiative/phenogrid/pull/250>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/monarch-initiative/phenogrid/pull/250#event-722240442>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADfUb_t-roIdCq30isWDpCCoqvEVhIF5ks5qVV-MgaJpZM4JLtSj>
> .
>


-- 
----------------------------------
mcmurry.julie@gmail.com +1 805 455 5877 skype: mcmurry.julie git: jmcmurry
----------------------------------

**Pull request merged**
