### PR TITLE
Message 4 no match

### PR DESCRIPTION
**Pull request by yuanzhou**
The main purpose of this PR is to add a messaging reporting mechanism so Phenogrid outputs user-friendly messages upon the following cases:

- no simsearch data returned from regular simsearch for species based on the config
- no simsearch data returned from the "compare" query
- no associated genotype found of a specific gene ID
- no compare data returned from expended genotypes.
- message for misconfig

The documentation has also been updated with more examples.

@harryhoch please review and merge if no issues. Thanks!

### CODE REVIEW

**Comment by harryhoch** [comment]
Is there something I should be looking at here? Or should I just check to ensure that nothing is broken?

**Comment by yuanzhou** [comment]
Please just check the `index.html` examples and I think those examples capture all the no-data cases except the genotype expansion (since the message will show in popup).

**Comment by harryhoch** [comment]
ok. generally looks good, but I tried to force a misconfig/no simsarch data, by changing taxon ids to grid number 1. This didn't work - I just see "Loading phenogrid widget" and the spinner. 

Can you add some tests to the test suite to verify that all of these error messages are provided when appropriate?

**Comment by yuanzhou** [comment]
Thanks for the suggestion! Currently the misconfig only triggers message upon misconfig of the `crossComparisonView` and `active` parameters. I'll add the taxon ID check for no simsearch data. Not sure how to add tests for those specific WBPhenotype IDs, I'll think about it.

**Comment by harryhoch** [comment]
sounds good. let me know when you're ready for me to review again

**Comment by yuanzhou** [comment]
@harryhoch, is there a place that you can point me to see a full list of species name with corresponding taxon IDs? I also reproduced the error you noticed by using an invalid taxon ID. In order to notify the users this misconfig message, we'll need to check the provided taxon ID against a pool. One simple workaround is to hard code this species-taxon list. But I don't know how long the full list will be.

**Comment by yuanzhou** [comment]
@harryhoch after playing around and thinking about this config check, I realized that there are more config check details involved.

```
targetGroupList: [
                {name: "Homo sapiens", taxon: "9606", crossComparisonView: true, active: true},
                {name: "Mus musculus", taxon: "10090", crossComparisonView: true, active: true},
                {name: "Danio rerio", taxon: "7955", crossComparisonView: true, active: true},
                {name: "Drosophila melanogaster", taxon: "7227", crossComparisonView: false, active: false},
                {name: "Caenorhabditis elegans", taxon: "6239", crossComparisonView: false, active: false},
                {name: "UDPICS", taxon: "UDPICS", crossComparisonView: false, active: false} 
            ]
```

This is the current targetGroupList config, it's the default one if there's no one specified in the constructor. When there's a targetGroupList in the constructor, it will overwrite this default one. That also means we'll need to check the user-provided targetGroupList to make sure it matches the desired schema. For example, in addition to check the `taxon` ID to make sure it's valid, we'll also need to check 9606 is in the same object that  "Homo sapiens" is specified. And we'll also have to check to make sure `crossComparisonView` and `active` present there too and their values are bools.

So I think we should just follow the "Convention over configuration" and explicitly tell the users how to config. I've refined the documentation. I think it's good to be merged.

**Comment by harryhoch** [comment]
ok, @yuanzhou, your point is a good one. However, tests are now failing. Please take a loo...

**Comment by yuanzhou** [comment]
@harryhoch refreshed the Travis Ci build, and it passed this time. I've noticed that sometimes the Travis CI fails and if you refresh it it passes again. Could be some monarch server issue at that build moment.

**Pull request merged**
