### PR TITLE
Genotype expansion - working but disabled for now

### PR DESCRIPTION
**Pull request by yuanzhou**
1. Refactored the tooltiprender and cleaned up the code
2. Added genotype expansion functionalities in dataManager, dataLoader, as well as phenogrid
3. Removed the use of apiEntityMap from phenogrid and dataLoader after the issue was address in the monarch api level
4. Cached the loaded genotype data for later re-expansion use
5. Highlighted added genotype lables and corresponding matching grid cells
6. Disabled the genotype expansion feature in tooltiprender before the api issues get addressed.

@harryhoch in this PR, the genotype expansion feature has been added with many corresponding changes in the code. I simply disabled this feature since we are still waiting for couple of api issues to be addressed. I think we can merge this PR to the master because with the genotype expansion feature disabled, all other features are still working correctly. Once the PR is merged, I can work on the mini-map and adding columns though the UI control. This way, we don't have to worry about the potential huge merging conflicts mess if I make changes based on the current master and come back to merge the genotype expansion branch later. And once the api issues are addressed, I can test the genotype expansion feature again and enable it easily.

### CODE REVIEW

**Comment by harryhoch** [comment]
@yuanzhou, let's discuss this. I'm seeing two problems:

1. dialogs for config and unmatched phenotypes aren't going away.
2. I'm not seeing the genotype expansion links.

**Comment by yuanzhou** [comment]
@harryhoch 

1. We need to click the unmatched button and the config/options button to hide the dialog.

2. I've disabled the genotype expansion in the tooltiprender so you won't see them.

**Comment by yuanzhou** [comment]
@harryhoch as you've suggested, I'll add a [close X] to the unmatched and control panel upper right corner to make this more intuitive and less guess work.

**Comment by yuanzhou** [comment]
The [Close X] button has been added in PR #212

**Pull request merged**
