### PR TITLE
Scrollbars

### PR DESCRIPTION
**Pull request by yuanzhou**
This branch was created in order to implement the vertical and horizontal scrollbars to enhance the navigation of phenogrid.

1. Scrollbars trigger the updates of grid region as well as the mini map shaded area movement

2. Mini map shaded area movements trigger the movements of scrollbars too

3. All the config of scrollbars are grouped as internalOptions for easy customization. 

4. Scrollbars' show/hide is controlled by the x count and y count of grid region

5. Refined the target group divider lines creation by perfectly position the divider lines. The old version doesn't calculate the accurate position. (the error is not visible since we only use 3 species for testing)

6. Also fixed mouseover conflicts during dragging the minimap and scrollbars

7. Added behave tests for checking the appearance of scrollbars

8. Code cleanup and refinement during the process

@harryhoch please install this branch and play with the scrollbars. And let me know if you have any suggestions. Thanks!

### CODE REVIEW

**Comment by harryhoch** [comment]
Looks great, @yuanzhou - thanks!

**Comment by yuanzhou** [comment]
Thanks @harryhoch, for the December release purpose (https://github.com/monarch-initiative/monarch-app/milestones), I won't update the npm version today. I plan to work on the adaptive columns re-sizing (based on the actual display area size) and push all the new features to npm at once with a MAJOY or MINOR version change. New features include:

- scrollbars
- genotype expansion (disabled currently)
- adaptive columns re-sizing

I'll need your input on whether to update the MAJOR or MINOR version by then.

**Comment by harryhoch** [comment]
ok. seems to me that these are all minor versions.

**Comment by yuanzhou** [comment]
Thanks @harryhoch.

**Pull request merged**
